language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - py.test --doctest-modules esy -v --cov esy --cov-report term-missing tests
after_success:
  - coveralls
